<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="Neepa-Laptop" failures="1" tests="3" name="Test" time="14.322" errors="0" timestamp="2024-03-25T20:42:59 MST">
  <testcase classname="tests.create_order_test" name="create_Order_test" time="5.861"/>
  <testcase classname="tests.Test_Customer_Login" name="customerlogin" time="2.114">
    <skipped/>
  </testcase> <!-- customerlogin -->
  <testcase classname="tests.Test_Employee_Login" name="emplogin" time="2.193">
    <failure type="java.lang.AssertionError" message="expected [Employee Id: 1002] but found [Employee Id: 102]">
      <![CDATA[java.lang.AssertionError: expected [Employee Id: 1002] but found [Employee Id: 102]
at tests.Test_Employee_Login.emplogin(Test_Employee_Login.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- emplogin -->
  <testcase classname="base.Base" name="@AfterSuite close_All" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite close_All -->
  <testcase classname="base.Base" name="@BeforeSuite startUp" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite startUp -->
  <testcase classname="base.Base" name="@AfterSuite close_All" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite close_All -->
  <testcase classname="base.Base" name="@BeforeSuite startUp" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite startUp -->
</testsuite> <!-- Test -->
